del /S "*.ncb"
del /S "*.pch"
del /S "*.obj"
del /S "*.idb"
del /S "*.pdb"
del /S "*.ilk"
del /S "*.aps"
del /S "*.dep"
del /S "*.manifest.*"
del /S "*.exe"
del /S "*.htm"
del /S "*.rsp"
del /S "*.exp"
del /S "*.enc"
del /S "*.tmp"
del /S "*.res"
del /S "*.dll"
del /S "*.exe"
del /S "*.sdf"
del /S "*.log"
del /S "*.tlog"
del /S "*.suo"
del /S /A:H "*.suo"

del /S "*log.txt"
del /S "sxLib.lib"
del /S "sxEngine.lib"
del /S "version1\sxEditor\*.lib"
del /S "version1\cnep\*.lib"
del /S "version1\plumbumCity\*.lib"
del /S "version1\rob_fa\*.lib"
del /S "version2\sxEditor\*.lib"
del /S "version2\sxConsole\*.lib"

pause