-- DROP TABLE IF EXISTS authen;

CREATE TABLE IF NOT EXISTS authen
(
	profile_id		INT UNSIGNED AUTO_INCREMENT UNIQUE PRIMARY KEY,
	device			VARCHAR(32) DEFAULT NULL,
	google 			VARCHAR(32) DEFAULT NULL,
	facebook	 	VARCHAR(32) DEFAULT NULL,
	username		VARCHAR(32) DEFAULT NULL,
	password		VARCHAR(32) DEFAULT NULL,
    register_date 	TIMESTAMP	
);